### PR TITLE
Minor improvements of map importer

### PR DESCRIPTION
**Pull request by RTAzis**
Added sharing of already loaded images among materials.
Ability to not import of GTA Sa LOD objects, grouping of identical models and some additional exceptions to prevent import stop for the map importer.
Equals for class properties was replaced with a single colon to follow Blender 2.8 required syntax.

### CODE REVIEW

**Comment by Zarig** [comment]
@swift502 @RTAzis Do any of you want to make any more changes to this, or is it ready to be merged?

**Comment by swift502** [comment]
@Zarig Not me, I abandoned this some time ago unfortunately.

In the traditional non-profit open-source fashion I woke up one day and found that I have suddenly no motivation to continue working on this and moved on to other things... ☹️

**Comment by RTAzis** [comment]
@Zarig I don’t know what else I can improve or add, so It can be merged.

**Comment by Blood-PawWerewolf** [comment]
status on TXD importing? because that’s all i can see that needs to be implemented...

**Comment by swift502** [comment]
Well magic-txd is also [open-source](https://github.com/quiret/magic-txd)). I didn't look too deep into it, but if it has any kind of API for reading and converting TXDs it shouldn't be too hard use it as a library right?

**Comment by Zarig** [comment]
I was working on TXD import, but I'd like to finish Collisions and multi-clump support first.

**Pull request merged**
